### ISSUE TITLE
Server doesn't work 

### ISSUE THREAD

**Issue by V1t3r** [Goujer/kanojo_app#55]
server runs in debian 10(python 3.7)
last working version of server 0.3.2
that what 0.3.4 and 0.3.3 responds on launch:
Traceback (most recent call last):
  File "web_job.py", line 20, in <module>
    from activity import FILL_TYPE_HTML
  File "/home/v1t3r/kanojo_server-0.3.4/activity.py", line 13, in <module>
    from web_job import getCategoryText
  File "/home/v1t3r/kanojo_server-0.3.4/web_job.py", line 20, in <module>
    from activity import FILL_TYPE_HTML
ImportError: cannot import name 'FILL_TYPE_HTML' from 'activity' (/home/v1t3r/kanojo_server-0.3.4/activity.py)

**Comment by Goujer** [comment]
I have made some code changes that seem to resolve the circular import issue.
Not sure why this wasn't being ran into on my server, but it should be working now.

**Comment by V1t3r** [comment]
now this
 Traceback (most recent call last):
  File "web_job.py", line 27, in <module>
    from user import *
  File "/home/v1t3r/kanojo_server-master/user.py", line 21, in <module>
    from activity import ActivityManager, ACTIVITY_SCAN, ACTIVITY_GENERATED, ACTIVITY_ME_ADD_FRIEND, ACTIVITY_APPROACH_KANOJO, ACTIVITY_ME_STOLE_KANOJO, ACTIVITY_MY_KANOJO_STOLEN, ACTIVITY_MY_KANOJO_ADDED_TO_FRIENDS, ACTIVITY_BECOME_NEW_LEVEL, ACTIVITY_MARRIED, ACTIVITY_JOINED, ACTIVITY_BREAKUP, ACTIVITY_ADD_AS_ENEMY
  File "/home/v1t3r/kanojo_server-master/activity.py", line 13, in <module>
    from web_job import getCategoryText
  File "/home/v1t3r/kanojo_server-master/web_job.py", line 58, in <module>
    activity_manager = ActivityManager(db=db)
NameError: name 'ActivityManager' is not defined

**Comment by Goujer** [comment]
I pushed a new commit, sorry for the wait. Try that out and let me know how it is.

**Comment by Goujer** [comment]
I would also like to know, are you using the app with https enabled?
I was thinking of raising the target SDK version to 28  or higher but that would make plain http unusable.

**Comment by V1t3r** [comment]
Seems server works fine now. I'm using http, don't tried https. Also: did the store works?(Got"server not responding") Also if u need something to test or discuss find me at telegram @v1t3r

**Comment by V1t3r** [comment]
Also if u need something to test or discuss find me at telegram @v1t3r

**Comment by Goujer** [comment]
@V1t3r I do not have Telegram, but I have Twitter and Discord (and a private Alpha group on Discord if you're interested.)
I have not gotten the store working yet, but it will be my next focus.
I will try and keep a HTTP compatible version of the app working so people don't have to worry about getting TLS certificates to host their own servers.

**Comment by teasouse** [comment]
Ubuntu 22.04.1 LTS
Python 3.10.6

getting same respond as [V1t3r](https://github.com/V1t3r)

When cloning a repo I'm getting this:

Traceback (most recent call last):
  File "/home/ubuntu/kanojo_server/web_job.py", line 56, in <module>
    kanojo_manager = KanojoManager(db,
  File "/home/ubuntu/kanojo_server/kanojo.py", line 78, in __init__
    if self.db and self.db.seqs.find_one({ 'collection': 'kanojos' }) is None:
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pymongo/database.py", line 1161, in __bool__
    raise NotImplementedError(
NotImplementedError: Database objects do not implement truth value testing or bool(). Please compare with None instead: database is not None

**Comment by Goujer** [comment]
Did someone comment on this?

**Comment by teasouse** [comment]
I'm not sure It's my fault or some new modules from requirements.txt conflicts with older ones. I changed the >= to == in it, installed again and that fixed the issue.

**Comment by Goujer** [comment]
> I'm not sure It's my fault or some new modules from requirements.txt conflicts with older ones. I changed the >= to == in it, installed again and that fixed the issue.

Thank you for this. I really should be using == and not >= because quite a few things have broken due to that.
